// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSRConfigs(arg1) {
  return window['go']['main']['App']['CheckSRConfigs'](arg1);
}

export function IsFirstLoad() {
  return window['go']['main']['App']['IsFirstLoad']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function PlayPortal2(arg1, arg2) {
  return window['go']['main']['App']['PlayPortal2'](arg1, arg2);
}

export function SaveFilePath(arg1) {
  return window['go']['main']['App']['SaveFilePath'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function SetFirstLoadComplete() {
  return window['go']['main']['App']['SetFirstLoadComplete']();
}
