// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckSRConfigs(arg1:boolean):Promise<void>;

export function IsFirstLoad():Promise<boolean>;

export function LoadState():Promise<main.AppState>;

export function PlayPortal2(arg1:boolean,arg2:string):Promise<string>;

export function SaveAutoreset(arg1:Array<number>,arg2:string):Promise<string>;

export function SaveFilePath(arg1:string):Promise<void>;

export function SaveState(arg1:main.AppState):Promise<void>;

export function SetFirstLoadComplete():Promise<void>;
